addSbtPlugin("org.scoverage"      % "sbt-scoverage"            % "1.5.1")
addSbtPlugin("pl.project13.scala" % "sbt-jmh"                  % "0.3.2")
addSbtPlugin("com.47deg"          % "sbt-microsites"           % "0.7.13")
addSbtPlugin("com.eed3si9n"       % "sbt-unidoc"               % "0.4.1")
addSbtPlugin("org.scala-js"       % "sbt-scalajs"              % "0.6.19")
addSbtPlugin("org.portable-scala" % "sbt-crossproject"         % "0.3.0")
addSbtPlugin("org.portable-scala" % "sbt-scalajs-crossproject" % "0.3.0")
